/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benuka
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
            String d1=null;
            String d2=null;
            String d3=null;
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(1280, 768));
        setMinimumSize(new java.awt.Dimension(1280, 768));
        setPreferredSize(new java.awt.Dimension(1280, 768));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Room No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "101", "102", "103", "104", "105", "106", "107", "108" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(200, 120, 70, 26);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(200, 170, 70, 26);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(270, 170, 70, 26);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", " " }));
        jComboBox4.setSelectedIndex(1);
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(340, 170, 90, 26);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Checkin Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 120, 19);

        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("DD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 150, 30, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("MM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 150, 30, 16);

        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("YYYY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 150, 40, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/search long.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/login/search long1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 170, 160, 50);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 590, 520, 80);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust_ID", "First Name", "Room No", "Total Amount", "Payment status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(28, 5, 730, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 270, 790, 160);

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 450, 460, 60);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Back.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Back2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(920, 580, 110, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Payments.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 1300, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
           
      DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
      String DATE=(String)jComboBox2.getSelectedItem();
      String MONTH = (String)jComboBox3.getSelectedItem();
      String YEAR=(String)jComboBox4.getSelectedItem();
      
                      
                 String D1=YEAR+"-"+MONTH+"-"+DATE;
                    
                    
                
      String Rmn=(String)jComboBox1.getSelectedItem();;
     
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
            conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Ivory","root","");
            String query="select CustID,Res_ID,Room_No from Reservation where CheckIN_Date='"+D1+"' and Room_No='"+Rmn+"';";
            
            PreparedStatement st=conn.prepareStatement(query);
            String d1 = null;
            String d2 = null;
            String d3 = null;
            ResultSet rs=st.executeQuery();
            
            while(rs.next()){
                
                 d1=rs.getString("CustID");
                 d2=rs.getString("Res_ID");
                d3=rs.getString("Room_No");
                
                
                //model.addRow(new Object []{d1,d2,d3});
            } 
            String query2="Select Total,Status from Payment where Res_ID='"+d2+"';";
            PreparedStatement st2=conn.prepareStatement(query2);
              ResultSet rs1=st2.executeQuery();
            
            while(rs1.next()){
                
                String d4=rs1.getString("Total");
                 String d5=rs1.getString("Status");
                
                model.addRow(new Object []{d1,d2,d3,d4,d5});
            } 
            
            
            
 
            rs.close();
            st.close();
            conn.close();
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this,e);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText("Payment Successfull");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainDashboard md=new MainDashboard();
        md.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
